### ISSUE TITLE
Regex does not match start position in line with "^blabla"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Woundorf/foxreplace#38] opened 2015-08-21 18:00 UTC
```
What steps will reproduce the problem?
1. Create a regex substitution for word "TODO" on first position in a line.
Regex: ^TODO  Replace: BlaFasel
2. Edit a TWiki page (normal textbox), write the word TODO in a single line
3. Hit F2 to apply the substitutions

What is the expected output? What do you see instead?
The substitution should replace the word TODO at the first position of a
line with the string "BlaFasel". But nothing happens.

What version of the product are you using? On what operating system?
0.12.2   Ubunutu 

Please provide any additional information below.
It seems as if the regex interpreter does not know the syntax for beginning
of aline.

```

Original issue reported on code.google.com by `i...@martinheinemann.net` on 27 Apr 2010 at 7:37

**Comment by Woundorf** [comment] 2016-01-26 10:08
Closing as duplicate of #95.

**Closed by Woundorf** 2016-01-26 10:08 UTC
Labels: auto-migrated, bug, duplicate, priority-medium
