### ISSUE TITLE
Please ADD some method to identify start-end of text line

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#255] opened 2018-08-29 05:04 UTC
Currently, all identification in text id done through regex coding, in which the method of identifying start/ end of text lines is very cryptic. (separated by cr or lf or cr-lf)

I think fr considers entire text as a single line, so I guess the regex codes of ^ $ to identify start/ end of line don't work that way in fr.

That makes me face problem as I need to identify start/ end of line (cr-lf) very often.

A user here has earlier given a working method, but that has too many codes and If found I can't put all those codes so many times in each conversion string.

So, I suggest fr ADDs some method of easy identification of start/ end of line, "which is over and above all coding of regex".

Thanks.

**Comment by SaltatorMortis** [comment] 2018-08-29 06:05
at this moment you could simply use [\r\n] and (?=[\r\n]) for start/ end of line (the lookahead if you have to get 2 lines in succession)

**Comment by Woundorf** [comment] 2018-09-04 17:56
Duplicate of #95.

**Closed by Woundorf** 2018-09-04 17:56 UTC
