### ISSUE TITLE
Enhancement: auto-detect editing boxes

### ISSUE THREAD

**Issue by Fabian42** [Woundorf/foxreplace#378] opened 2024-09-07 07:33 UTC
I am unsure how exactly this would be done and it can probably never be perfect, but it would be nice if the extension could at least attempt to detect when I am editing other people's texts and then not apply substitutions there. Apparently I just accidentally edited a bunch of other people's comments on a wiki's talk page, without realising. I know that I can manually exclude entire sites, but that would be a lot of websites and some of them have in-place editing, so there would be no way to have the substitutions applied when viewing content, but not when editing it. A somewhat simple solution would be an option to just exclude all text input boxes.

**Comment by Woundorf** [comment] 2024-09-23 15:39
The simple solution is what is proposed in #56, so I'll mark this as a duplicate of that.

**Closed as not planned by Woundorf** 2024-09-23 15:39 UTC
Labels: duplicate
