### ISSUE TITLE
Enhancement suggestion: whitelist pages from replacing only on load

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Woundorf/foxreplace#140] opened 2015-08-21 18:01 UTC
```
Hi, I'd like to suggest an enhancement in the address whitelisting feature, so 
that it could exclude from replacing on page load, but if clicked on FoxReplace 
icon, it could work. Currently, if a page address is whitelisted, the replacing 
function doesn't work unless the page link is removed from the list. 
In my case, I have some pages that I don't want to replace on page load so that 
it doesn't freeze Firefox, but sometimes I want to replace the page text using 
my substitution list, but this is  not possible, because it's whitelisted.

I don't know if there's a way to do that, but it would be very good.
```

Original issue reported on code.google.com by `brunolop...@gmail.com` on 3 Jun 2014 at 7:47

**Comment by Woundorf** [comment] 2019-05-23 18:42
Duplicate of #206.

**Closed by Woundorf** 2019-05-23 18:42 UTC
Labels: OpSys-All, auto-migrated, enhancement, logic, performance, persistence, priority-low, ui
