### ISSUE TITLE
ff 55.0.1 fr options Enable column not working

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#219] opened 2017-08-21 18:02 UTC
in ff v55.0.1 latest fr release - in fr options, Enable column not working

![fr1](https://user-images.githubusercontent.com/8685207/29531981-9d6f3206-86c8-11e7-82db-a44ab547753c.jpg)

The tick marks are not visible,
When I go to "Edit" on a substitution table, Enable is ticked there, but not appearing as ticked in Enalbe column.

mouse click on Enable column doesn't bring (or remove) tickmark.

newly imported tables have no tick mark visible in Enable column.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment] 2017-08-21 18:28
Duplicate of #217. As I said there, I'm not going to fix it because the new version should be approved soon (it's currently third in the review queue).

**Closed by Woundorf** 2017-08-21 18:28 UTC
Labels: duplicate
