### ISSUE TITLE
0.17.2. fails on Mac OSX

### ISSUE THREAD

**Issue by JohnFHall** [Woundorf/foxreplace#184] opened 2016-09-29 22:51 UTC
Can you please add 0.17.3 on the Development Channel so I can see if it fixed replace fail in 0.17.2
0.17.1.1 had worked well for me!
Note: 0.17.2 fails for me on both Windows 7 (VMware Fusion VM) and Mac OSX.

**Comment by kimcarver** [comment] 2016-09-30 00:28
Having same problem with Find/Replace since release of 0.17.2 on Mac OSX 10.9.5.

**Comment by JohnFHall** [comment] 2016-09-30 00:43
I've rolled back to 0.17.1.1 by finding the fox@replace.fx.xpi in the extension folder from another (older Virtual Machine) and installing that. In FF in about:config I then set extensions.update.enabled to false to prevent 0.17.2 re-installing. I guess I'll have to keep checking here to see if the "update" is corrected !

**Comment by JohnFHall** [comment] 2016-09-30 11:39
Good afternoon. Use FoxReplace every day as it is an indispensable tool for my work but today, when entering the page I use have observed that though enabled the plugin (always have active) has not worked, has not made any replacement text (and it has not appeared any error) and do not understand what could have happened. I retested deactivating / activating complement, uninstalling / installing it again and even tried on another computer and can not get it to work. I think there has been an update in recent days, but yesterday I worked perfectly, this may be the reason? Please let me please indicate what can be caused this and how I could fix it. Thanks in advance.

**Comment by JohnFHall** [comment] 2016-09-30 11:39
Oops! Still open!

**Comment by Woundorf** [comment] 2016-09-30 11:48
Duplicate of #183. A new version has already been published, but it's still awaiting review. In the meantime you can install a previous version from here: https://addons.mozilla.org/firefox/addon/foxreplace/versions/. Sorry for the inconvenience.

**Closed by Woundorf** 2016-09-30 11:48 UTC
Labels: duplicate

**Comment by JohnFHall** [comment] 2016-09-30 12:06
The provided link only allows the installation of 0.17.3; as previously said I have found a way to install 0.17.1.1, and it works ok

**Comment by Woundorf** [comment] 2016-09-30 12:08
The provided link allows to install any version if you scroll down.

**Comment by JohnFHall** [comment] 2016-09-30 12:16
Marc,
Sorry, I didn't scroll down far enough. Thank you for your excellent speedy help.
John
