### ISSUE TITLE
Issue with "Apply automatic substitutions on page load" Firefox Quantum

### ISSUE THREAD

**Issue by TheCubeUser** [Woundorf/foxreplace#240] opened 2018-04-08 11:41 UTC
Under Firefox Quantum, (59.01) When I enable "Apply automatic substitutions on page load", on some pages, like Youtube, it has no effect, probably because Foxreplace tries to apply the substitutes ASAP since the page loads. But some web sites may load the content dynamically once the page is loaded. I then have to use the "Apply automatic substitutions every [1] seconds", which can cause the browser to hang or other strange behaviour. The solution would be to add an option to delay the substitution for X seconds since after page load, or to repeat it every X seconds but for a limited amount of times

**Comment by Woundorf** [comment] 2018-04-08 17:08
Duplicate of #51.

**Closed by Woundorf** 2018-04-08 17:08 UTC
Labels: duplicate
