### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Maren4499** [Woundorf/foxreplace#191] opened 2016-10-04 11:21 UTC
Hi there,

I really love your Add-On and use it all the time. But recently, after the last update on September 30th, 2016, I always get an error message: "ReferenceError: can't access lexical declaration `oldValue' before initialization" - although the text I wanted to replace is being replaced correctly. It only annoys me that I have to click OK every single time.

![error](https://cloud.githubusercontent.com/assets/22614765/19072406/572a5860-8a35-11e6-86de-44bd1edc36a6.jpg)

I'm using Firefox 49.0.1 German version.

Please help!

Cheers, Maren

**Comment by Woundorf** [comment] 2016-10-05 11:24
Duplicate of #183. This is a bug introduced in 0.17.2 while fixing a problem with Firefox 49. It's solved in the next version that was published published several days ago but it's still awaiting review. So I can only tell you to wait a few more days until it's approved. Sorry for the inconvenience.

**Closed by Woundorf** 2016-10-05 11:24 UTC
