### ISSUE TITLE
Apply automatic substitutions resetting itself.

### ISSUE THREAD

**Issue by Merseybuoy** [Woundorf/foxreplace#243] opened 2018-05-30 08:01 UTC
I have 'Apply automatic substitutions' set to 15 seconds. When I go to the options page, I find it has changed itself to 1 second. Using FoxReplace 2.2.0 and Firefox 61 beta.

With storage.js open in Notepad++, I can see when the file is changed. It appears that simply opening the options page is causing the value of "autoReplacePeriod": to reset to 1.

I don't use the Periodically update from URL section, but if Period (minutes) is changed to another value, that is also reset to 1 when the options page is opened.

**Comment by Woundorf** [comment] 2018-06-03 11:31
I haven't been able to reproduce it yet. Does this still happen to you?

**Comment by Merseybuoy** [comment] 2018-06-05 06:02
Hi Marc,

Yes, it's still happening. After reading your email I opened the options page from the toolbar icon. Apply automatic substitutions is ticked and set to 15 seconds (that's how I left it last time). I then refresh the options page and the 15 seconds changes to 1 second. Reinstalling does not fix it. I have to set storage.js to read-only to allow me to check my filters without the change occurring.

**Comment by Merseybuoy** [comment] 2018-07-01 10:50
I've gone back to version 2.1.0 (with save button) and the problem has gone. What I am seeing though is when I do a ctrl+F5 refresh, the setting changes to 1 second briefly and then reverts to 15 seconds. I guess the auto-save in v.2.2.0 is causing my problem?

**Comment by Woundorf** [comment] 2018-07-02 16:14
I still can't reproduce this with 2.2.0. Doing Ctrl+F5 it behaves as you say, setting it to 1 second for a moment but then returning to the saved value. What operating system do you use (just in case it is some platform-specific issue)?

**Comment by Merseybuoy** [comment] 2018-07-02 17:06
Windows 10 Home, 1803, 64bit. Intel i7. All up to date. To me it just felt like the auto-save is 'capturing' that brief glimpse of the '1 second' and then not returning to the '15 seconds'.

**Comment by JanisE** [comment] 2018-10-27 11:47
Setting other value than 1s doesn't seem to have any effect (Firefox 63 for Linux).

Even if I set it to 5 seconds and switch to a page, I see that the replacement is being done every 1 second. And when I restart the browser, the option has been reset back to 1 s, too.

**Comment by Woundorf** [comment] 2018-10-28 16:08
I still can't reproduce it (Firefox 64.0b4 on Windows 7, I will try it on Linux later).

**Comment by Woundorf** [comment] 2018-11-22 16:17
Do you have enabled the "update periodically from URL" option?

**Comment by Merseybuoy** [comment] 2018-11-22 17:02
I don't, Marc. I did try it as a test as I mentioned in my first post. I've happily stayed with version 2.1.0 since then.

**Comment by Woundorf** [comment] 2018-11-22 17:40
Ok, I just found a similar issue in 2.2.0 when that option is enabled, and coincidentally it was fixed with a change that I did months ago but was not released in any version yet. I have now uploaded a new version (2.2.1) with that change and a few more. If you have a moment to try it please tell me if this issue still happens or not.

**Comment by Merseybuoy** [comment] 2018-11-22 19:06
After an hours testing, I haven't been able to break it yet. Looking good. Thanks. I'll let you know if it fails.

**Comment by Woundorf** [comment] 2018-11-23 18:51
Good! Then I will close this issue for now. If you manage to break it I will reopen it.

**Closed by Woundorf** 2018-11-23 18:51 UTC
Labels: bug
