### ISSUE TITLE
Home-End buttons do not work in the Substitutions entries' fields.

### ISSUE THREAD

**Issue by iG8R** [Woundorf/foxreplace#372] opened 2024-04-01 14:53 UTC
In fact, the title says for itself.

[FoxReplace-Home-End-dont-work-Video_2024-04-01_17-40-43.webm](https://github.com/Woundorf/foxreplace/assets/11407417/e11c4c00-0deb-4d62-8a9e-7e01f9931b84)

**Comment by Woundorf** [comment] 2024-04-01 14:59
Duplicate of #276, but certainly very annoying.

**Closed as not planned by Woundorf** 2024-04-01 14:59 UTC
Labels: duplicate
