### ISSUE TITLE
New error message

### ISSUE THREAD

**Issue by SimonVilleneuvewp** [Woundorf/foxreplace#186] opened 2016-09-30 14:41 UTC
Hi,

First, thank you very much for this tool. It is very helpfull. I use it mainly for translations on Wikipedia.

Unfortunately, the tool didn't work at all for me since yesterday. I have this error message : "ReferenceError: can't access lexical declaration `oldValue' before initialization". I tried the "T" and "RE" options, with and without regex, but no results.

Before that, for about 2 days, the tool only work for one expression at a time in the page. I was force to click "Replace" to change every expression one by one on the page.
Maybe I have changed of Firefox version and the bug is coming from there. I'm now on the 49.0.1 version.

**Comment by Woundorf** [comment] 2016-10-01 13:57
Duplicate of #183. A new version has already been published, but it's still awaiting review. In the meantime you can install a previous version from here: https://addons.mozilla.org/firefox/addon/foxreplace/versions/. Sorry for the inconvenience.

**Closed by Woundorf** 2016-10-01 13:57 UTC
Labels: duplicate

**Comment by SimonVilleneuvewp** [comment] 2016-10-02 01:15
Thank you very much. It work now (but on Firefox developper edition).


Do you know when it will be signed ?


Thanks again for this wonderful tool.


Simon


________________________________
De : Marc Ruiz <notifications@github.com>
Envoyé : 1 octobre 2016 09:57
À : Woundorf/foxreplace
Cc : SimonVilleneuvewp; Author
Objet : Re: [Woundorf/foxreplace] New error message (#186)


Duplicate of #183<https://github.com/Woundorf/foxreplace/issues/183>. A new version has already been published, but it's still awaiting review. In the meantime you can install a previous version from here: https://addons.mozilla.org/firefox/addon/foxreplace/versions/. Sorry for the inconvenience.

-

**Comment by Woundorf** [comment] 2016-10-02 08:08
It's currently in position 62 of 96, but it says that addons are not reviewed strictly in order.

**Comment by SimonVilleneuvewp** [comment] 2016-10-02 12:27
Ok. Merci encore.


________________________________
De : Marc Ruiz <notifications@github.com>
Envoyé : 2 octobre 2016 04:08
À : Woundorf/foxreplace
Cc : SimonVilleneuvewp; Author
Objet : Re: [Woundorf/foxreplace] New error message (#186)


It's currently in position 62 of 96, but it says that addons are not reviewed strictly in order.

-
