### ISSUE TITLE
Maintain case

### ISSUE THREAD

**Issue by seize21** [Woundorf/foxreplace#197] opened 2016-11-15 20:13 UTC
The Chrome variant of this is Word Replacer ll. There is a useful feature that I would like to see in FoxReplace. It's called maintain case. It will essentially try to maintain the case of the original text. Say you have ‘look‘ converted to ‘bees’, the sentence ‘Look here.’ will be converted to ‘Bees here.’ in Word Replacer ll. In FoxReplace, it will return ‘bees here.’

I suggest this because I want to port my list of 400+ substitutions, and manually typing them is impracticable.

**Comment by SaltatorMortis** [comment] 2016-11-16 06:54
this is no special feature you can have this with a simple regular Expression:
`Look( here)`
with the output  
`bees$1`

**Comment by Woundorf** [comment] 2016-11-16 20:36
Duplicate of #82.

**Closed by Woundorf** 2016-11-16 20:36 UTC
