### ISSUE TITLE
Can't access lexical declaration 'oldValue' before initialization

### ISSUE THREAD

**Issue by ohei2** [Woundorf/foxreplace#192] opened 2016-10-09 12:40 UTC
Hi,

I am a happy user since a couple of years, but recently FoxReplace stopped working for me at all.

I always get the above error message when I initiate the actual replace (enter or button click). I reinstalled the addon. It did not help.

Regards

![20161009143024](https://cloud.githubusercontent.com/assets/22726761/19220480/2b7efbd8-8e2e-11e6-9670-d609e35d4ffa.png)

**Comment by ohei2** [comment] 2016-10-09 12:45
I'll add that before the above happened 14 days ago or so, FoxReplace started to merely replace one occurrence at a time, so I had to enter/click through all occurrences of the search term, i.e. 5 occurrences => 5 clicks.

I probably should have reported this earlier, sorry.

**Comment by Woundorf** [comment] 2016-10-09 13:59
Duplicate of #183. The error from several days ago happens with Firefox 49 or later, and was fixed in 0.17.2, but it introduced a new error which is the one that you are finding now. A newer version (0.17.3) was published two days later (10 days ago) to fix that, but it's still awaiting review (this time is really slow, I don't know why). You can get the new version from https://addons.mozilla.org/firefox/addon/foxreplace/versions/, but it can only be installed in Firefox Developer Edition or a nightly. Sorry for the inconvenience.

**Closed by Woundorf** 2016-10-09 13:59 UTC
Labels: duplicate
