### ISSUE TITLE
FoxReplace stopped working

### ISSUE THREAD

**Issue by wisark** [Woundorf/foxreplace#185] opened 2016-09-30 11:32 UTC
Buenas tardes. Utilizo FoxReplace todos los días ya que es una herramienta indispensable para mi trabajo pero hoy, al entrar a la página en que lo uso he observado que pese a estar activado el plugin (siempre lo tengo activo) no ha funcionado, no ha hecho ningún reemplazo de texto (y tampoco ha aparecido ningún error) y no entiendo qué ha podido ocurrir. He vuelto a probar desactivando/activando el complemento,   desinstalandolo/instalandolo otra vez e incluso probado en otro ordenador y no logro que funcione. Creo que ha habido una actualización en los últimos días, aunque ayer mismo me funcionaba perfectamente, ¿puede que sea este el motivo? Le agradecería me indicara por favor a qué puede deberse esto y como podría solucionarlo. Gracias por adelantado.

**Comment by JohnFHall** [comment] 2016-09-30 11:38
In English (roughly): **Good afternoon. Use FoxReplace every day as it is an indispensable tool for my work but today, when entering the page I use have observed that though enabled the plugin (always have active) has not worked, has not made any replacement text (and it has not appeared any error) and do not understand what could have happened. I retested deactivating / activating complement, uninstalling / installing it again and even tried on another computer and can not get it to work. I think there has been an update in recent days, but yesterday I worked perfectly, this may be the reason? Please let me please indicate what can be caused this and how I could fix it. Thanks in advance.**

**Comment by wisark** [comment] 2016-09-30 11:45
Hello JohnFHall, I am really sorry, I thought I could write in spanish, so my apologies for that matter. The translation is quite good.

**Comment by JohnFHall** [comment] 2016-09-30 11:49
Google Translate is good! Buenas tardes.

**Comment by Woundorf** [comment] 2016-09-30 11:53
Duplicate of #183. A new version has already been published, but it's still awaiting review. In the meantime you can install a previous version from here: https://addons.mozilla.org/firefox/addon/foxreplace/versions/. Sorry for the inconvenience.

@wisark Puedes escribir en castellano si quieres, ningún problema.

@JohnFHall The translation was not needed, but thank you.

**Closed by Woundorf** 2016-09-30 11:53 UTC
Labels: duplicate

**Comment by JohnFHall** [comment] 2016-09-30 11:59
I cannot install from supplied link, even though I have xpinstall.signatures.required set to false

**Comment by Woundorf** [comment] 2016-09-30 12:00
You can't install 0.17.3 because it's still awaiting review, but you should be able to install 0.17.1.
