### ISSUE TITLE
Please give option to import/save CSV or TAB DELI file, instead of .json

### ISSUE THREAD

**Issue by vsrawat** [Woundorf/foxreplace#172] opened 2016-01-21 03:09 UTC
.json file is having very strict coding, and has expanded forms for every option, like "casesensitive", "regex".

And then it has field names.

When all these are fixed info, please consider giving an option so that we can import bare data from a CSV or TAB DELI file, instead of a .json file. 

Then your code itself fills out field names, etc.

Also, a single digit or numeral code can be given for "casesensitive", "regex" "whole word" type of options, to further reduce on the info to be provided.

All that is known to your program, so avoid asking the json file to provide that.

And then, you can also give option to save as a a CSV or TAB DELI file, instead of a .json file. so that we can directly open that in excel etc, and work further.

Thanks.
-- 
Rawat

**Comment by Woundorf** [comment] 2016-01-21 10:09
This is a duplicate of #91.

Maybe I will add an option to import from csv, but it will be very limited because of the nature of the format, which is suited to tabular data, while FoxReplace uses tree data. An export option to csv is discarded.

**Closed by Woundorf** 2016-01-21 10:09 UTC
Labels: duplicate
