### ISSUE TITLE
Option to disable entry in right-click menu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Woundorf/foxreplace#128] opened 2015-08-21 18:01 UTC
```
What steps will reproduce the problem?

1. Right-click in a page


What is the expected output? What do you see instead?

I would like to be able to disable FoxReplace's entry in the right-click menu 
for web pages. 


What version of the product are you using? On what operating system?

0.15.0. On Linux.


Please provide any additional information below.

Please consider shortening its text too, it makes the right-click menu in 
Firefox considerably larger.
```

Original issue reported on code.google.com by `misu.mol...@gmail.com` on 4 Oct 2013 at 9:15

**Comment by Woundorf** [comment] 2019-05-23 18:40
Duplicate of #229 (in fact that should have been the duplicate of this).

**Closed by Woundorf** 2019-05-23 18:40 UTC
Labels: OpSys-All, auto-migrated, enhancement, priority-medium, ui
