### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by FrisbyDoof** [Woundorf/foxreplace#187] opened 2016-10-01 07:05 UTC
Starting a few days ago FoxReplace stopped working. In the browser console I'm getting this error: ReferenceError: can't access lexical declaration `oldValue' before initialization. 
![error 1](https://cloud.githubusercontent.com/assets/22556954/19012483/ce84bcea-877c-11e6-9dc4-014ffc23f072.PNG)

**Comment by Woundorf** [comment] 2016-10-01 13:58
Duplicate of #183. A new version has already been published, but it's still awaiting review. In the meantime you can install a previous version from here: https://addons.mozilla.org/firefox/addon/foxreplace/versions/. Sorry for the inconvenience.

**Closed by Woundorf** 2016-10-01 13:58 UTC
Labels: duplicate
