### ISSUE TITLE
Substition groups past group #1 no long working for me?

### ISSUE THREAD

**Issue by Lemons224** [Woundorf/foxreplace#193] opened 2016-10-11 08:35 UTC
I haven't used this addon for a while, but when I tried to use it again today I noticed that any substitutions that don't reside in the top substitution group are simply ignored! Furthermore, if I move a sub group to the top suddenly it's substitutions will work again, but if I move it back out of the top position...even to second position, then BAM! The substitutions in that group will no longer work. This is a HUGE bug for me considering I have 20 substitution groups! All filled with substitutions that are no longer applied! Please fix.

**Comment by Woundorf** [comment] 2016-10-11 18:19
Duplicate of #179 or #183. Both are fixed in version 0.17.3 which was published 12 days ago, but it's still awaiting review (exceptionally slow, I don't know why). You can get the new version from https://addons.mozilla.org/firefox/addon/foxreplace/versions/, but it can only be installed in Firefox Developer Edition or a nightly. Sorry for the inconvenience.

**Closed by Woundorf** 2016-10-11 18:19 UTC
Labels: duplicate
