### ISSUE TITLE
Only the first group works fully

### ISSUE THREAD

**Issue by charlietg** [Woundorf/foxreplace#189] opened 2016-10-02 12:23 UTC
Been using this for about a year with pretty much no problem, like it very much. However, very recently it stopped applying most of my filters, and after playing around it seems the add-on only applies the top group, and mostly (but not always) ignores the others. The ones that don't replace, even if I re-make the whole entry, don't work unless the group placed at the top, but that leaves other groups taking over the problem. 

Using the latest FF and FR builds.

**Comment by Woundorf** [comment] 2016-10-02 14:52
Duplicate of #183. A new version has already been published, but it's still awaiting review. In the meantime you can install a previous version from here: https://addons.mozilla.org/firefox/addon/foxreplace/versions/. Sorry for the inconvenience.

**Closed by Woundorf** 2016-10-02 14:52 UTC
