### ISSUE TITLE
Can you add adaptive characters (upper and lower case) checkbox in "substitutions"

### ISSUE THREAD

**Issue by Nemzag** [Woundorf/foxreplace#268] opened 2019-03-06 19:31 UTC
Hi,
we can use "Match case",
but if I need to replace "FOR", "for", "For", by "PRO", "pro", "Por" I need to make three substitution…
Can you make a new option to have adaptive case ?
Like this, we will be able to make one substitution, who will use automatically use the right CASE size based on the CASE used in the visited page… 
Please.
Thank you.

**Comment by Woundorf** [comment] 2019-03-06 19:33
Duplicate of #82.

**Closed by Woundorf** 2019-03-06 19:33 UTC

**Comment by henryzshao** [comment] 2021-09-17 18:14
I'm a bit confused. Is the issue solved?

**Comment by Woundorf** [comment] 2021-09-18 15:07
No, it's the same as #82 and that is not implemented yet.

**Comment by Nemzag** [comment] 2021-09-20 07:57
I see you talk here,
dô‑n’t forget my new proposal :

> Also here is some of my new suggestion and old one’s :
> To avoid useless change, in different languages (with word of same combination with differenet meaning) :
> Take consideration of html lang=sq parameter, substitution list !

Tʰank.
