### ISSUE TITLE
Can't select Regular Expressions in 1280x720 displays

### ISSUE THREAD

**Issue by enzog1** [Woundorf/foxreplace#267] opened 2019-02-24 20:24 UTC
The window interface size is too big to fit in on my screen and Regular Expressions cannot be selected.

**Comment by Woundorf** [comment] 2019-02-25 17:01
Can you post a screenshot? When it's at the bottom of the screen it should open upwards.

**Comment by enzog1** [comment] 2019-02-27 15:13
Sorry for the late reply, it does open  upwards from the bottom of the screen as you say, Woundorf, but when I click regular expression then click away from the screen to confirm the window closes and discards my changes and I'm sent back to the Substitution List window.
I found a workaround by using the arrow keys to select and then Enter key to confirm.
 
![Uploading 2019-02-27 12_12_24.jpg…]()

**Comment by Woundorf** [comment] 2019-02-27 15:28
Ok, from the screenshot I see the problem is in fact the same as in #248, because the type selector moves far away to the bottom and then you can't click out of it without closing the window.

**Closed by Woundorf** 2019-02-27 15:28 UTC
Labels: bug, ui
